### ISSUE TITLE
Could not find property 'v2SigningEnabled' on SigningConfig_Decorated

### ISSUE THREAD

**Issue by Aarontaken** [shwenzhang/AndResGuard#148]
添加 v2SigningEnabled false 后：
Could not find method v2SigningEnabled() for arguments [false] on SigningConfig_Decorated
studio 2.1.2 须要升级？

**Comment by imknown** [comment]
好像最近挺多人 问这个问题, 我看 最近关掉的 几个 issues 也有问题 v2 的..

**Comment by simpleton** [comment]
对，这个应该是新加的property，不过如果你低版本的gradle tools应该也不用增加这个属性就会使用V1签名

On Apr 5, 2017 5:28 PM, "Aaron Wang" <notifications@github.com> wrote:

添加 v2SigningEnabled false 后：
Could not find method v2SigningEnabled() for arguments [false] on
SigningConfig_Decorated
studio 2.1.2 须要升级？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shwenzhang/AndResGuard/issues/148>, or mute the thread

**Comment by simpleton** [comment]
@imknown 主要google这块升级不需要改任何配置，很多同学并不知道自己用了v2。但是如果使用了v2，7zip暂时是无法生效的。所以安装包的压缩程度会比以前低一些。

**Comment by imknown** [comment]
@simpleton 嗯 确实, 查了一下, 升级之后 默认会开启.
https://developer.android.com/about/versions/nougat/android-7.0.html#apk_signature_v2

**Comment by Aarontaken** [comment]
@simpleton 嗯 我更新下studio看看

**Comment by simpleton** [comment]
@Aarontaken 升级或者不升级都OK。看你是想要极小的安装包，还是使用v2签名。使用v2签名安装速度回快一些，并且可以方式一些应用商店的2次打包。

**Comment by Aarontaken** [comment]
@simpleton 嗯你说的是v2签名的好处和极小的安装包的矛盾吧，但还是得升级studio到2.2以上避免运行Andresguard tasks报上面的两种错吧！

**Comment by simpleton** [comment]
@Aarontaken 报错的问题我也修复下，多谢issue。
ref #149

**Comment by simpleton** [comment]
@Aarontaken 您这边还有旧版本，可以尝试下把版本号更新到1.2.1。

**Comment by Aarontaken** [comment]
嗯可以了 非常感谢！
